services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: tasksync
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5555:5432
    networks:
      - tasksync
    restart: unless-stopped
  keycloak:
    image: keycloak/keycloak:26.2
    ports:
      - 9090:8080
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      JAVA_OPTS_APPEND: >
        - XX:+UseG1GC
        - XX:+AggressiveOpts
    networks:
      - tasksync
    command: ["start-dev"]
    depends_on:
      - postgres

networks:
  tasksync:
    driver: bridge

volumes:
  postgres:
    driver: local
  keycloak:
    driver: local