services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: tasksync
    volumes:
      - postgres:/data/postgres
    ports:
      - 5555:5432
    networks:
      - tasksync
    restart: unless-stopped
  keycloak:
    image: keycloak/keycloak:26.2
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - tasksync
    command:
      - "start-dev"
networks:
  tasksync:
    driver: bridge

volumes:
  postgres:
    driver: local
  keycloak:
    driver: local