spring:
  cors:
    allowed-origin: ${CORS_ALLOWED_ORIGIN}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}
  session:
    jdbc:
      table-name: SPRING_SESSION
      initialize-schema: always
    timeout: 1800
  application:
    name: tasksync
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    web:
      pageable:
        max-page-size: 100
    rest:
      max-page-size: 100
  profiles:
    default: prod
keycloak:
  server-url: ${KEYCLOAK_SERVER_URL}
  realm: ${KEYCLOAK_REALM}
  clientId: ${KEYCLOAK_CLIENT_ID}
  clientSecret: ${KEYCLOAK_CLIENT_SECRET}